export const actions = {
  SET_OWNER_FORM_COLLAPSED: "SET_OWNER_FORM_COLLAPSED",
  SET_OWNER: "SET_OWNER",
  SET_TOKEN: "SET_TOKEN",
  FETCH_REPOS: "FETCH_REPOS",
  SET_REPOS: "SET_REPOS",

  SET_REPO_FORM_COLLAPSED: "SET_REPO_FORM_COLLAPSED",
  SET_REPO: "SET_REPO",
  FETCH_BRANCHES: "FETCH_BRANCHES",
  SET_BRANCHES: "SET_BRANCHES",

  SET_BRANCH_FORM_COLLAPSED: "SET_BRANCH_FORM_COLLAPSED",
  SET_BRANCH: "SET_BRANCH",
  FETCH_FILES: "FETCH_FILES",
  BUILD_TREE: "BUILD_TREE",

  SET_RENDERER: "SET_RENDERER",
  REDRAW: "REDRAW",
  SET_HOVERED_NODE: "SET_HOVERED_NODE",
  SET_MAIN_NODE: "SET_MAIN_NODE",
};
